# Generated by Django 2.0.10 on 2019-01-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad_curricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('trayecto', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
