# Generated by Django 2.0.10 on 2019-01-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unidad_curricular',
        ),
    ]
