# Generated by Django 2.0.10 on 2019-01-23 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDeAcceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDeSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ilustracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='ilustraciones')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fechadeenvio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDisponibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePrivilegios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificador', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredeusuario', models.CharField(max_length=120, unique=True)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('correoelectronico', models.CharField(max_length=200)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Gender')),
                ('fechadenacimiento', models.DateField()),
                ('niveldeprivilegios', models.IntegerField(default=0)),
                ('contrasea', models.CharField(max_length=50)),
                ('fechadereg', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechadeacceso', models.DateTimeField(blank=True, null=True)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoDeDisponibilidad')),
                ('estadodeacceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.EstadoDeAcceso')),
                ('imagendeperfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ilustracion')),
                ('privilegios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoDePrivilegios')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aspiraciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoDePrivilegios'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.EstadoDeSolicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
