# Generated by Django 2.0.10 on 2019-02-10 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenidos', '0007_auto_20190210_0228'),
        ('usuarios', '0002_auto_20190123_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Gender')),
                ('fecha_de_nacimiento', models.DateField()),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoDeDisponibilidad')),
                ('estado_de_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.EstadoDeAcceso')),
                ('imagen_de_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ilustracion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado_de_acceso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imagen_de_perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='privilegios',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
