# Generated by Django 2.1.5 on 2019-02-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190210_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, default='../media/default/perfil.png', max_length=255, upload_to='../media/perfiles'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='aspiraciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
