# Generated by Django 2.0.10 on 2019-01-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areadelsaber',
            old_name='fechamodif',
            new_name='fecha_de_modificacion',
        ),
        migrations.RenameField(
            model_name='areadelsaber',
            old_name='fechareg',
            new_name='fecha_de_registro',
        ),
        migrations.RemoveField(
            model_name='areadelsaber',
            name='ilustracionprimaria',
        ),
        migrations.RemoveField(
            model_name='areadelsaber',
            name='ilustracionsecundaria',
        ),
        migrations.AddField(
            model_name='areadelsaber',
            name='ilustracion_primaria',
            field=models.ImageField(max_length=255, null=True, upload_to='../media/ilustraciones'),
        ),
        migrations.AddField(
            model_name='areadelsaber',
            name='ilustracion_secundaria',
            field=models.ImageField(max_length=255, null=True, upload_to='../media/ilustraciones'),
        ),
    ]
